### ISSUE TITLE
Ex21.java (CPF2)

### ISSUE THREAD

**Issue by kyriosdata** [vnduda/cs-2019-01#12]
Nas linhas 21 e 22 são definidas duas CONSTANTES, não são variáveis. Em Java você terá que usar o **final** antes do **int** para indicar que são constantes. Isto é o mesmo que #10, que já foi observado antes. 

Também altere o nome dos arquivos, **Ex21.java** deveria ser CpfAlternativo.java, se não preferir outro nome. Isto tem relação com #7.

**Comment by vnduda** [comment]
Foi corrigido
