### ISSUE TITLE
Melhorado em f781a93af67fa6c4c977179a3b861590c59eec4d

### ISSUE THREAD

**Issue by kyriosdata** [vnduda/cs-2019-01#13]
Melhorado em f781a93af67fa6c4c977179a3b861590c59eec4d

_Originally posted by @vnduda in https://github.com/vnduda/cs-2019-01/issues/10#issuecomment-491567524_

No código em Java, das linhas 562 até 568 temos vários casos semelhantes, agora em Java. É preciso fazer o equivalente, neste caso com o uso **final**.

**Comment by vnduda** [comment]
Resolvido -> 4cfe30e81a5e35a77782a12e6616f8babcce5eec
