### ISSUE TITLE
Visibilidade das suas funções

### ISSUE THREAD

**Issue by kyriosdata** [vnduda/cs-2019-01#6]
Uma forma de dividir o código em JavaScript é como está fazendo, contudo, para que a função seja visível externamente, em outros módulos, uma possibilidade é acrescentar

```javascript
module.exports = propriedade153;
```
ao final do arquivo, neste caso, **Ex02.js**. 
Esta recomendação tem alguma relação com #4

**Comment by vnduda** [comment]
Corrigido em 9aa11537b37dfc38a8fe66d2e5fd7590f3e2bc16
